[package]
name = "loop_benchmark_rust"
version = "0.1.0"
edition = "2018"

[dependencies]
ctrlc = "3.1.9"
rustc_version = "0.3.3"
num-format = "0.4.0"
num_cpus = "1.13.0"
nix = "0.20.0"

[[bin]]
name = "loop_benchmark_rust"
path = "loop_benchmark.rs"